; 2. Write a program to input n (input from keyboard) strings of characters with the length unlimited (it is defined by the program, not by the compiler). 
; Sort them in descending or ascending order depending on the request input.
; Attention: 
; These strings are sorted in ascending/descending by the order of dictionary with deleting 
; redundant characters in each string: blank ' ', comma ',' if they exist in string. 
;
; Author: Vy Duc Kien
; ID: 1951010
; Date: 01/05/2021

;string length: 5
				
	.ORIG	x3000
	LD	R1, START
	LD	R3, LENGTH
	AND	R4, R4, #0
	BR	#4
NEW_S	LD	R3, LENGTH
	LD	R1, START_NEW
	ADD	R1, R1, R3
	ADD	R1, R1, #1
	ST	R1, START_NEW
	LEA	R0, MES
	PUTS
LOOP	GETC
	LD	R2, ENTER
	ADD	R2, R0, R2
	BRz	PR_STRING
	LD	R2, SPACE
	ADD	R2, R0, R2
	BRz	NEW_S
	OUT
	STR	R0, R1, #0
	ADD	R1, R1, #1
	ADD	R3, R3, #-1
	BRz	NEW_S
	BR	LOOP
PR_STRING
	JSR	SORT
	JSR	SORT_ALPHABET
	LEA	R0, OUTP
	PUTS
	LD	R0, START
	ST	R0, START_NEW
gay
	LEA	R0, newline
	PUTS
	LD	R0, START_NEW
	PUTS
	ADD	R0, R0, #6
	ST	R0, START_NEW
	LDI	R2, START_NEW
	BRz	DONE
	BRp	gay
DONE	HALT
START	.FILL	X4000
START_NEW	.FILL	X4000
SORT_END	.FILL	X4006
ENTER	.FILL	X-A
SPACE	.FILL	X-20
LENGTH	.FILL	X5
MES	.STRINGZ "\nENTER A STRING: "
OUTP	.STRINGZ "\nSORTED ORDER: "
newline	.STRINGZ "\n"

SORT	ST	R7, SAVER7
SORT_NEW
	LD	R0, START_ORIG_0
	ST	R0, START_SORT
	LD	R0, END_ORIG_0
	ST	R0, START_END

BEGIN	LD	R0, START_SORT	;LOAD THE ADDRESS OF THE FIRST CHARACTER IN THE FIRST STRING
	LDR	R1, R0, #0	;LOAD THE FIRST CHARACTER IN THE FIRST STRING
	LD	R0, START_END
	LDR	R2, R0, #0
	JSR	COMP		;NEGATE R2
	ADD	R3, R1, R2	
	BRnz	DO_THIS		;if already sorted, compare next word
SWAP_INIT_0
;INIT BEFORE SWAPPING
	LD	R5, LENGTH
	LD	R0, START_SORT
	ST	R0, SWAP_START
	LD	R0, START_END
	ST	R0, SWAP_END
	LD	R7, SAVER7
SWAP_WORD_0
	LD	R0, SWAP_START
	LDR	R1, R0, #0
	LD	R0, SWAP_END
	LDR	R2, R0, #0
	;SWAP PLACES
	STR	R1, R0, #0
	LD	R0, SWAP_START
	STR	R2, R0, #0
	LD	R0, SWAP_START
	ADD	R0, R0, #1
	ST	R0, SWAP_START
	LD	R0, SWAP_END
	ADD	R0, R0, #1
	ST	R0, SWAP_END
	ADD	R5, R5, #-1
	BRzp	SWAP_WORD_0
	BR	SORT_NEW
DO_THIS:
	LD	R0, START_END
	ADD	R0, R0, #6
	ST	R0, START_END
	LDR	R1, R0, #0
	BRz	INCRE_START
	BR	BEGIN

INCRE_START
	LD	R0, START_ORIG_0
	ADD	R0, R0, #6
	ST	R0, START_ORIG_0
	ADD	R0, R0, #6
	ST	R0, END_ORIG_0
	LDR	R0, R0, #0
	BRz	FINISH
	BR	SORT_NEW
FINISH	LD	R7, SAVER7
	RET

COMP	NOT	R2, R2
	ADD	R2, R2, #1
	RET

SORT_OFFSET	.FILL	X4006
START_ORIG_0	.FILL	X4000
START_ORIG	.FILL	X4000
END_ORIG_0	.FILL	X4006
END_ORIG	.FILL	X4006

SORT_ALPHABET
	ST	R7, SAVER7
compare_beg_init
	LD	R0, START_ORIG
	ST	R0, START_SORT
	LD	R0, END_ORIG
	ST	R0, START_END
compare_beg
	LD	R0, START_SORT
	LDR	R1, R0, #0
	ST	R1, BEG_CHAR
	LD	R0, START_END
	LDR	R2, R0, #0
	JSR	COMP
	ADD	R3, R1, R2 
	BRz	goto_nextchar_init	;if two beginning match, compare next char
	BRn	increase_start

goto_nextchar_init
	LD	R0, START_SORT
	ST	R0, START_SORT_NEXT_CHAR
	LD	R0, START_END
	ST	R0, START_END_NEXT_CHAR
goto_nextchar
	
	LD	R0, START_SORT_NEXT_CHAR
	ADD	R0, R0, #1
	ST	R0, START_SORT_NEXT_CHAR
	LDR 	R1, R0, #0

	LD	R0, START_END_NEXT_CHAR
	ADD	R0, R0, #1
	ST	R0, START_END_NEXT_CHAR
	LDR	R2, R0, #0
	JSR	COMP
	ADD	R3, R1, R2
	BRz	goto_nextchar	;if two words have the same beginning character, proceed to compare the next characters
	BRp	SWAP_INIT
	BRn	goto_nextword	;if already sorted, compare next word

SWAP_INIT
;INIT BEFORE SWAPPING
	LD	R5, LENGTH
	LD	R0, START_SORT
	ST	R0, SWAP_START
	LD	R0, START_END
	ST	R0, SWAP_END
	LD	R7, SAVER7
SWAP_WORD
	LD	R0, SWAP_START
	LDR	R1, R0, #0
	LD	R0, SWAP_END
	LDR	R2, R0, #0
	;SWAP PLACES
	STR	R1, R0, #0
	LD	R0, SWAP_START
	STR	R2, R0, #0
	
	;INCREASE SWAP ADDRESS
	LD	R0, SWAP_START
	ADD	R0, R0, #1
	ST	R0, SWAP_START
	LD	R0, SWAP_END
	ADD	R0, R0, #1
	ST	R0, SWAP_END
	ADD	R5, R5, #-1
	BRzp	SWAP_WORD
	BR	compare_beg_init
goto_nextword
	LD	R0, START_END
	ADD	R0, R0, #6
	ST	R0, START_END
	LDR	R1, R0, #0
	LD	R2, BEG_CHAR
	JSR	COMP
	ADD	R3, R1, R2
	BRz  	compare_beg
	BRp	increase_start	
increase_start
	LD	R0, START_ORIG
	ADD	R0, R0, #6
	ST	R0, START_ORIG
	ADD	R0, R0, #6
	ST	R0, END_ORIG
	LDR	R1, R0, #0
	BRz	FINISH_SORT
	BR	compare_beg_init
FINISH_SORT
	LD	R7, SAVER7
	RET	

END	.FILL	X4006
START_SORT	.FILL	X4000
START_SORT_NEXT_CHAR	.FILL	X4000
START_OFFSET	.FILL	X4000
START_END	.FILL	X4006
START_END_NEXT_CHAR	.FILL	X4006

BEG_CHAR	.BLKW	1
SWAP_START	.FILL	X4000
SWAP_END	.FILL	X4006
SAVER7	.BLKW	1
.END